//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PomodoroZamanlayiciUI.Properties {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PomodoroZamanlayiciUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Ayarlar&gt;
        ///  &lt;Tercihler&gt;
        ///    &lt;KalanSure&gt;true&lt;/KalanSure&gt;
        ///    &lt;Cal&gt;true&lt;/Cal&gt;
        ///    &lt;OtomatikBaslat&gt;false&lt;/OtomatikBaslat&gt;
        ///    &lt;Pomodoro&gt;25&lt;/Pomodoro&gt;
        ///    &lt;KisaAra&gt;05&lt;/KisaAra&gt;
        ///    &lt;UzunAra&gt;10&lt;/UzunAra&gt;
        ///  &lt;/Tercihler&gt;
        ///&lt;/Ayarlar&gt; benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Ayarlar {
            get {
                return ResourceManager.GetString("Ayarlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pomodoro Zamanlayıcı programı çalışırken aşağıdaki kısayol tuşlarına basarak, istediğiniz işlemleri klavye üzerinden de yapabileceğinizi biliyor muydunuz?
        ///
        ///* İpucu: Baş harfleri takip edin.
        ///
        ///&gt; Başlat: B
        ///&gt; Dur: D
        ///&gt; Sıfırla: S
        ///&gt; Pomodoro: P
        ///&gt; Kısa Ara: K
        ///&gt; Uzun Ara: U benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Kisayollar {
            get {
                return ResourceManager.GetString("Kisayollar", resourceCulture);
            }
        }
    }
}
